version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nginx_practice
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
